name: Minecraft-Player-UUID
version: '${project.version}'
main: fr.koi.minecraftplayeruuid.MinecraftPlayerUuid
api-version: 1.18
description: A simple plugin to allow minecraft server administrators to get player UUID
commands:
  uuid:
    description: "Display UUID of the specified player"
    usage: /uuid <player>

permissions:
  uuid.*:
    description: Grants the ability to use all commands from the Minecraft-Player-UUID plugin
    children:
      uuid.uuid:
        description: Allows the use of the /uuid command
